
export type Country = {
  name: string;
  code: string;
  currency: string;
  currencySymbol: string;
};

export const countries: Country[] = [
  // Africa (54 countries)
  { name: 'Algeria', code: 'DZ', currency: 'DZD', currencySymbol: 'د.ج' },
  { name: 'Angola', code: 'AO', currency: 'AOA', currencySymbol: 'Kz' },
  { name: 'Benin', code: 'BJ', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Botswana', code: 'BW', currency: 'BWP', currencySymbol: 'P' },
  { name: 'Burkina Faso', code: 'BF', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Burundi', code: 'BI', currency: 'BIF', currencySymbol: 'FBu' },
  { name: 'Cabo Verde', code: 'CV', currency: 'CVE', currencySymbol: 'Esc' },
  { name: 'Cameroon', code: 'CM', currency: 'XAF', currencySymbol: 'FCFA' },
  { name: 'Central African Republic', code: 'CF', currency: 'XAF', currencySymbol: 'FCFA' },
  { name: 'Chad', code: 'TD', currency: 'XAF', currencySymbol: 'FCFA' },
  { name: 'Comoros', code: 'KM', currency: 'KMF', currencySymbol: 'CF' },
  { name: 'Congo, Democratic Republic of the', code: 'CD', currency: 'CDF', currencySymbol: 'FC' },
  { name: 'Congo, Republic of the', code: 'CG', currency: 'XAF', currencySymbol: 'FCFA' },
  { name: 'Cote d\'Ivoire', code: 'CI', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Djibouti', code: 'DJ', currency: 'DJF', currencySymbol: 'Fdj' },
  { name: 'Egypt', code: 'EG', currency: 'EGP', currencySymbol: 'E£' },
  { name: 'Equatorial Guinea', code: 'GQ', currency: 'XAF', currencySymbol: 'FCFA' },
  { name: 'Eritrea', code: 'ER', currency: 'ERN', currencySymbol: 'Nfk' },
  { name: 'Eswatini', code: 'SZ', currency: 'SZL', currencySymbol: 'L' },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', currencySymbol: 'Br' },
  { name: 'Gabon', code: 'GA', currency: 'XAF', currencySymbol: 'FCFA' },
  { name: 'Gambia', code: 'GM', currency: 'GMD', currencySymbol: 'D' },
  { name: 'Ghana', code: 'GH', currency: 'GHS', currencySymbol: 'GH₵' },
  { name: 'Guinea', code: 'GN', currency: 'GNF', currencySymbol: 'FG' },
  { name: 'Guinea-Bissau', code: 'GW', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Kenya', code: 'KE', currency: 'KES', currencySymbol: 'KSh' },
  { name: 'Lesotho', code: 'LS', currency: 'LSL', currencySymbol: 'L' },
  { name: 'Liberia', code: 'LR', currency: 'LRD', currencySymbol: 'L$' },
  { name: 'Libya', code: 'LY', currency: 'LYD', currencySymbol: 'LD' },
  { name: 'Madagascar', code: 'MG', currency: 'MGA', currencySymbol: 'Ar' },
  { name: 'Malawi', code: 'MW', currency: 'MWK', currencySymbol: 'MK' },
  { name: 'Mali', code: 'ML', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Mauritania', code: 'MR', currency: 'MRU', currencySymbol: 'UM' },
  { name: 'Mauritius', code: 'MU', currency: 'MUR', currencySymbol: '₨' },
  { name: 'Morocco', code: 'MA', currency: 'MAD', currencySymbol: 'DH' },
  { name: 'Mozambique', code: 'MZ', currency: 'MZN', currencySymbol: 'MT' },
  { name: 'Namibia', code: 'NA', currency: 'NAD', currencySymbol: 'N$' },
  { name: 'Niger', code: 'NE', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', currencySymbol: '₦' },
  { name: 'Rwanda', code: 'RW', currency: 'RWF', currencySymbol: 'R₣' },
  { name: 'Sao Tome and Principe', code: 'ST', currency: 'STN', currencySymbol: 'Db' },
  { name: 'Senegal', code: 'SN', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Seychelles', code: 'SC', currency: 'SCR', currencySymbol: '₨' },
  { name: 'Sierra Leone', code: 'SL', currency: 'SLL', currencySymbol: 'Le' },
  { name: 'Somalia', code: 'SO', currency: 'SOS', currencySymbol: 'S' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', currencySymbol: 'R' },
  { name: 'South Sudan', code: 'SS', currency: 'SSP', currencySymbol: '£' },
  { name: 'Sudan', code: 'SD', currency: 'SDG', currencySymbol: '£' },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', currencySymbol: 'TSh' },
  { name: 'Togo', code: 'TG', currency: 'XOF', currencySymbol: 'CFA' },
  { name: 'Tunisia', code: 'TN', currency: 'TND', currencySymbol: 'DT' },
  { name: 'Uganda', code: 'UG', currency: 'UGX', currencySymbol: 'USh' },
  { name: 'Zambia', code: 'ZM', currency: 'ZMW', currencySymbol: 'ZK' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', currencySymbol: '$' },
  // Rest of the world (100 countries)
  { name: 'Afghanistan', code: 'AF', currency: 'AFN', currencySymbol: '؋' },
  { name: 'Albania', code: 'AL', currency: 'ALL', currencySymbol: 'L' },
  { name: 'Argentina', code: 'AR', currency: 'ARS', currencySymbol: '$' },
  { name: 'Australia', code: 'AU', currency: 'AUD', currencySymbol: '$' },
  { name: 'Austria', code: 'AT', currency: 'EUR', currencySymbol: '€' },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT', currencySymbol: '৳' },
  { name: 'Belgium', code: 'BE', currency: 'EUR', currencySymbol: '€' },
  { name: 'Bolivia', code: 'BO', currency: 'BOB', currencySymbol: 'Bs.' },
  { name: 'Brazil', code: 'BR', currency: 'BRL', currencySymbol: 'R$' },
  { name: 'Bulgaria', code: 'BG', currency: 'BGN', currencySymbol: 'лв' },
  { name: 'Cambodia', code: 'KH', currency: 'KHR', currencySymbol: '៛' },
  { name: 'Canada', code: 'CA', currency: 'CAD', currencySymbol: '$' },
  { name: 'Chile', code: 'CL', currency: 'CLP', currencySymbol: '$' },
  { name: 'China', code: 'CN', currency: 'CNY', currencySymbol: '¥' },
  { name: 'Colombia', code: 'CO', currency: 'COP', currencySymbol: '$' },
  { name: 'Costa Rica', code: 'CR', currency: 'CRC', currencySymbol: '₡' },
  { name: 'Croatia', code: 'HR', currency: 'EUR', currencySymbol: '€' },
  { name: 'Cuba', code: 'CU', currency: 'CUP', currencySymbol: '$' },
  { name: 'Cyprus', code: 'CY', currency: 'EUR', currencySymbol: '€' },
  { name: 'Czech Republic', code: 'CZ', currency: 'CZK', currencySymbol: 'Kč' },
  { name: 'Denmark', code: 'DK', currency: 'DKK', currencySymbol: 'kr' },
  { name: 'Dominican Republic', code: 'DO', currency: 'DOP', currencySymbol: '$' },
  { name: 'Ecuador', code: 'EC', currency: 'USD', currencySymbol: '$' },
  { name: 'El Salvador', code: 'SV', currency: 'USD', currencySymbol: '$' },
  { name: 'Estonia', code: 'EE', currency: 'EUR', currencySymbol: '€' },
  { name: 'Fiji', code: 'FJ', currency: 'FJD', currencySymbol: '$' },
  { name: 'Finland', code: 'FI', currency: 'EUR', currencySymbol: '€' },
  { name: 'France', code: 'FR', currency: 'EUR', currencySymbol: '€' },
  { name: 'Georgia', code: 'GE', currency: 'GEL', currencySymbol: '₾' },
  { name: 'Germany', code: 'DE', currency: 'EUR', currencySymbol: '€' },
  { name: 'Greece', code: 'GR', currency: 'EUR', currencySymbol: '€' },
  { name: 'Guatemala', code: 'GT', currency: 'GTQ', currencySymbol: 'Q' },
  { name: 'Honduras', code: 'HN', currency: 'HNL', currencySymbol: 'L' },
  { name: 'Hong Kong', code: 'HK', currency: 'HKD', currencySymbol: '$' },
  { name: 'Hungary', code: 'HU', currency: 'HUF', currencySymbol: 'Ft' },
  { name: 'Iceland', code: 'IS', currency: 'ISK', currencySymbol: 'kr' },
  { name: 'India', code: 'IN', currency: 'INR', currencySymbol: '₹' },
  { name: 'Indonesia', code: 'ID', currency: 'IDR', currencySymbol: 'Rp' },
  { name: 'Iran', code: 'IR', currency: 'IRR', currencySymbol: '﷼' },
  { name: 'Iraq', code: 'IQ', currency: 'IQD', currencySymbol: 'ع.د' },
  { name: 'Ireland', code: 'IE', currency: 'EUR', currencySymbol: '€' },
  { name: 'Israel', code: 'IL', currency: 'ILS', currencySymbol: '₪' },
  { name: 'Italy', code: 'IT', currency: 'EUR', currencySymbol: '€' },
  { name: 'Jamaica', code: 'JM', currency: 'JMD', currencySymbol: 'J$' },
  { name: 'Japan', code: 'JP', currency: 'JPY', currencySymbol: '¥' },
  { name: 'Jordan', code: 'JO', currency: 'JOD', currencySymbol: 'JD' },
  { name: 'Kazakhstan', code: 'KZ', currency: 'KZT', currencySymbol: '₸' },
  { name: 'Kuwait', code: 'KW', currency: 'KWD', currencySymbol: 'KD' },
  { name: 'Latvia', code: 'LV', currency: 'EUR', currencySymbol: '€' },
  { name: 'Lebanon', code: 'LB', currency: 'LBP', currencySymbol: '£' },
  { name: 'Liechtenstein', code: 'LI', currency: 'CHF', currencySymbol: 'CHF' },
  { name: 'Lithuania', code: 'LT', currency: 'EUR', currencySymbol: '€' },
  { name: 'Luxembourg', code: 'LU', currency: 'EUR', currencySymbol: '€' },
  { name: 'Malaysia', code: 'MY', currency: 'MYR', currencySymbol: 'RM' },
  { name: 'Malta', code: 'MT', currency: 'EUR', currencySymbol: '€' },
  { name: 'Mexico', code: 'MX', currency: 'MXN', currencySymbol: '$' },
  { name: 'Monaco', code: 'MC', currency: 'EUR', currencySymbol: '€' },
  { name: 'Mongolia', code: 'MN', currency: 'MNT', currencySymbol: '₮' },
  { name: 'Nepal', code: 'NP', currency: 'NPR', currencySymbol: '₨' },
  { name: 'Netherlands', code: 'NL', currency: 'EUR', currencySymbol: '€' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD', currencySymbol: '$' },
  { name: 'Nicaragua', code: 'NI', currency: 'NIO', currencySymbol: 'C$' },
  { name: 'North Korea', code: 'KP', currency: 'KPW', currencySymbol: '₩' },
  { name: 'Norway', code: 'NO', currency: 'NOK', currencySymbol: 'kr' },
  { name: 'Oman', code: 'OM', currency: 'OMR', currencySymbol: '﷼' },
  { name: 'Pakistan', code: 'PK', currency: 'PKR', currencySymbol: '₨' },
  { name: 'Panama', code: 'PA', currency: 'PAB', currencySymbol: 'B/.' },
  { name: 'Paraguay', code: 'PY', currency: 'PYG', currencySymbol: '₲' },
  { name: 'Peru', code: 'PE', currency: 'PEN', currencySymbol: 'S/.' },
  { name: 'Philippines', code: 'PH', currency: 'PHP', currencySymbol: '₱' },
  { name: 'Poland', code: 'PL', currency: 'PLN', currencySymbol: 'zł' },
  { name: 'Portugal', code: 'PT', currency: 'EUR', currencySymbol: '€' },
  { name: 'Qatar', code: 'QA', currency: 'QAR', currencySymbol: '﷼' },
  { name: 'Romania', code: 'RO', currency: 'RON', currencySymbol: 'lei' },
  { name: 'Russia', code: 'RU', currency: 'RUB', currencySymbol: '₽' },
  { name: 'San Marino', code: 'SM', currency: 'EUR', currencySymbol: '€' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', currencySymbol: '﷼' },
  { name: 'Singapore', code: 'SG', currency: 'SGD', currencySymbol: '$' },
  { name: 'Slovakia', code: 'SK', currency: 'EUR', currencySymbol: '€' },
  { name: 'Slovenia', code: 'SI', currency: 'EUR', currencySymbol: '€' },
  { name: 'South Korea', code: 'KR', currency: 'KRW', currencySymbol: '₩' },
  { name: 'Spain', code: 'ES', currency: 'EUR', currencySymbol: '€' },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR', currencySymbol: '₨' },
  { name: 'Sweden', code: 'SE', currency: 'SEK', currencySymbol: 'kr' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', currencySymbol: 'CHF' },
  { name: 'Taiwan', code: 'TW', currency: 'TWD', currencySymbol: 'NT$' },
  { name: 'Thailand', code: 'TH', currency: 'THB', currencySymbol: '฿' },
  { name: 'Trinidad and Tobago', code: 'TT', currency: 'TTD', currencySymbol: 'TT$' },
  { name: 'Turkey', code: 'TR', currency: 'TRY', currencySymbol: '₺' },
  { name: 'Ukraine', code: 'UA', currency: 'UAH', currencySymbol: '₴' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED', currencySymbol: 'د.إ' },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP', currencySymbol: '£' },
  { name: 'United States', code: 'US', currency: 'USD', currencySymbol: '$' },
  { name: 'Uruguay', code: 'UY', currency: 'UYU', currencySymbol: '$U' },
  { name: 'Vatican City', code: 'VA', currency: 'EUR', currencySymbol: '€' },
  { name: 'Venezuela', code: 'VE', currency: 'VES', currencySymbol: 'Bs.' },
  { name: 'Vietnam', code: 'VN', currency: 'VND', currencySymbol: '₫' },
];

    