
export type Currency = {
  name: string;
  code: string;
  symbol: string;
};

export const currencies: Currency[] = [
  // 54 African Currencies
  { name: 'Algerian Dinar', code: 'DZD', symbol: 'د.ج' },
  { name: 'Angolan Kwanza', code: 'AOA', symbol: 'Kz' },
  { name: 'Botswana Pula', code: 'BWP', symbol: 'P' },
  { name: 'Burundian Franc', code: 'BIF', symbol: 'FBu' },
  { name: 'Cape Verdean Escudo', code: 'CVE', symbol: 'Esc' },
  { name: 'Central African CFA Franc', code: 'XAF', symbol: 'FCFA' },
  { name: 'West African CFA Franc', code: 'XOF', symbol: 'CFA' },
  { name: 'Comorian Franc', code: 'KMF', symbol: 'CF' },
  { name: 'Congolese Franc', code: 'CDF', symbol: 'FC' },
  { name: 'Djiboutian Franc', code: 'DJF', symbol: 'Fdj' },
  { name: 'Egyptian Pound', code: 'EGP', symbol: 'E£' },
  { name: 'Eritrean Nakfa', code: 'ERN', symbol: 'Nfk' },
  { name: 'Eswatini Lilangeni', code: 'SZL', symbol: 'L' },
  { name: 'Ethiopian Birr', code: 'ETB', symbol: 'Br' },
  { name: 'Gambian Dalasi', code: 'GMD', symbol: 'D' },
  { name: 'Ghanaian Cedi', code: 'GHS', symbol: 'GH₵' },
  { name: 'Guinean Franc', code: 'GNF', symbol: 'FG' },
  { name: 'Kenyan Shilling', code: 'KES', symbol: 'KSh' },
  { name: 'Lesotho Loti', code: 'LSL', symbol: 'L' },
  { name: 'Liberian Dollar', code: 'LRD', symbol: 'L$' },
  { name: 'Libyan Dinar', code: 'LYD', symbol: 'LD' },
  { name: 'Malagasy Ariary', code: 'MGA', symbol: 'Ar' },
  { name: 'Malawian Kwacha', code: 'MWK', symbol: 'MK' },
  { name: 'Mauritanian Ouguiya', code: 'MRU', symbol: 'UM' },
  { name: 'Mauritian Rupee', code: 'MUR', symbol: '₨' },
  { name: 'Moroccan Dirham', code: 'MAD', symbol: 'DH' },
  { name: 'Mozambican Metical', code: 'MZN', symbol: 'MT' },
  { name: 'Namibian Dollar', code: 'NAD', symbol: 'N$' },
  { name: 'Nigerian Naira', code: 'NGN', symbol: '₦' },
  { name: 'Rwandan Franc', code: 'RWF', symbol: 'R₣' },
  { name: 'São Tomé & Príncipe Dobra', code: 'STN', symbol: 'Db' },
  { name: 'Seychellois Rupee', code: 'SCR', symbol: '₨' },
  { name: 'Sierra Leonean Leone', code: 'SLL', symbol: 'Le' },
  { name: 'Somali Shilling', code: 'SOS', symbol: 'S' },
  { name: 'South African Rand', code: 'ZAR', symbol: 'R' },
  { name: 'South Sudanese Pound', code: 'SSP', symbol: '£' },
  { name: 'Sudanese Pound', code: 'SDG', symbol: '£' },
  { name: 'Tanzanian Shilling', code: 'TZS', symbol: 'TSh' },
  { name: 'Tunisian Dinar', code: 'TND', symbol: 'DT' },
  { name: 'Ugandan Shilling', code: 'UGX', symbol: 'USh' },
  { name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZK' },
  { name: 'Zimbabwean Dollar', code: 'ZWL', symbol: '$' },
  { name: 'Benin', code: 'XOF', symbol: 'CFA' },
  { name: 'Burkina Faso', code: 'XOF', symbol: 'CFA' },
  { name: 'Cameroon', code: 'XAF', symbol: 'FCFA' },
  { name: 'Central African Republic', code: 'XAF', symbol: 'FCFA' },
  { name: 'Chad', code: 'XAF', symbol: 'FCFA' },
  { name: 'Congo, Republic of the', code: 'XAF', symbol: 'FCFA' },
  { name: 'Cote d\'Ivoire', code: 'XOF', symbol: 'CFA' },
  { name: 'Equatorial Guinea', code: 'XAF', symbol: 'FCFA' },
  { name: 'Gabon', code: 'XAF', symbol: 'FCFA' },
  { name: 'Guinea-Bissau', code: 'XOF', symbol: 'CFA' },
  { name: 'Mali', code: 'XOF', symbol: 'CFA' },
  { name: 'Niger', code: 'XOF', symbol: 'CFA' },
  { name: 'Senegal', code: 'XOF', symbol: 'CFA' },
  { name: 'Togo', code: 'XOF', symbol: 'CFA' },

  // 100 Other World Currencies
  { name: 'United States Dollar', code: 'USD', symbol: '$' },
  { name: 'Euro', code: 'EUR', symbol: '€' },
  { name: 'Japanese Yen', code: 'JPY', symbol: '¥' },
  { name: 'British Pound', code: 'GBP', symbol: '£' },
  { name: 'Australian Dollar', code: 'AUD', symbol: '$' },
  { name: 'Canadian Dollar', code: 'CAD', symbol: '$' },
  { name: 'Swiss Franc', code: 'CHF', symbol: 'CHF' },
  { name: 'Chinese Yuan', code: 'CNY', symbol: '¥' },
  { name: 'Indian Rupee', code: 'INR', symbol: '₹' },
  { name: 'Brazilian Real', code: 'BRL', symbol: 'R$' },
  { name: 'Russian Ruble', code: 'RUB', symbol: '₽' },
  { name: 'Afghan Afghani', code: 'AFN', symbol: '؋' },
  { name: 'Albanian Lek', code: 'ALL', symbol: 'L' },
  { name: 'Argentine Peso', code: 'ARS', symbol: '$' },
  { name: 'Armenian Dram', code: 'AMD', symbol: '֏' },
  { name: 'Aruban Florin', code: 'AWG', symbol: 'ƒ' },
  { name: 'Azerbaijani Manat', code: 'AZN', symbol: '₼' },
  { name: 'Bahamian Dollar', code: 'BSD', symbol: '$' },
  { name: 'Bahraini Dinar', code: 'BHD', symbol: '.د.ب' },
  { name: 'Bangladeshi Taka', code: 'BDT', symbol: '৳' },
  { name: 'Barbadian Dollar', code: 'BBD', symbol: '$' },
  { name: 'Belarusian Ruble', code: 'BYN', symbol: 'Br' },
  { name: 'Belize Dollar', code: 'BZD', symbol: 'BZ$' },
  { name: 'Bermudian Dollar', code: 'BMD', symbol: '$' },
  { name: 'Bhutanese Ngultrum', code: 'BTN', symbol: 'Nu.' },
  { name: 'Bolivian Boliviano', code: 'BOB', symbol: 'Bs.' },
  { name: 'Bosnia-Herzegovina Convertible Mark', code: 'BAM', symbol: 'KM' },
  { name: 'Brunei Dollar', code: 'BND', symbol: '$' },
  { name: 'Bulgarian Lev', code: 'BGN', symbol: 'лв' },
  { name: 'Cambodian Riel', code: 'KHR', symbol: '៛' },
  { name: 'Cayman Islands Dollar', code: 'KYD', symbol: '$' },
  { name: 'Chilean Peso', code: 'CLP', symbol: '$' },
  { name: 'Colombian Peso', code: 'COP', symbol: '$' },
  { name: 'Costa Rican Colón', code: 'CRC', symbol: '₡' },
  { name: 'Croatian Kuna', code: 'HRK', symbol: 'kn' },
  { name: 'Cuban Peso', code: 'CUP', symbol: '$' },
  { name: 'Czech Koruna', code: 'CZK', symbol: 'Kč' },
  { name: 'Danish Krone', code: 'DKK', symbol: 'kr' },
  { name: 'Dominican Peso', code: 'DOP', symbol: 'RD$' },
  { name: 'East Caribbean Dollar', code: 'XCD', symbol: '$' },
  { name: 'Fijian Dollar', code: 'FJD', symbol: '$' },
  { name: 'Georgian Lari', code: 'GEL', symbol: '₾' },
  { name: 'Gibraltar Pound', code: 'GIP', symbol: '£' },
  { name: 'Guatemalan Quetzal', code: 'GTQ', symbol: 'Q' },
  { name: 'Guyanese Dollar', code: 'GYD', symbol: '$' },
  { name: 'Haitian Gourde', code: 'HTG', symbol: 'G' },
  { name: 'Honduran Lempira', code: 'HNL', symbol: 'L' },
  { name: 'Hong Kong Dollar', code: 'HKD', symbol: '$' },
  { name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft' },
  { name: 'Icelandic Króna', code: 'ISK', symbol: 'kr' },
  { name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp' },
  { name: 'Iranian Rial', code: 'IRR', symbol: '﷼' },
  { name: 'Iraqi Dinar', code: 'IQD', symbol: 'ع.د' },
  { name: 'Israeli New Shekel', code: 'ILS', symbol: '₪' },
  { name: 'Jamaican Dollar', code: 'JMD', symbol: 'J$' },
  { name: 'Jordanian Dinar', code: 'JOD', symbol: 'JD' },
  { name: 'Kazakhstani Tenge', code: 'KZT', symbol: '₸' },
  { name: 'Kuwaiti Dinar', code: 'KWD', symbol: 'KD' },
  { name: 'Kyrgystani Som', code: 'KGS', symbol: 'с' },
  { name: 'Lao Kip', code: 'LAK', symbol: '₭' },
  { name: 'Latvian Lats', code: 'LVL', symbol: 'Ls' },
  { name: 'Lebanese Pound', code: 'LBP', symbol: '£' },
  { name: 'Lithuanian Litas', code: 'LTL', symbol: 'Lt' },
  { name: 'Macanese Pataca', code: 'MOP', symbol: 'MOP$' },
  { name: 'Macedonian Denar', code: 'MKD', symbol: 'ден' },
  { name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM' },
  { name: 'Maldivian Rufiyaa', code: 'MVR', symbol: '.ރ' },
  { name: 'Mexican Peso', code: 'MXN', symbol: '$' },
  { name: 'Moldovan Leu', code: 'MDL', symbol: 'L' },
  { name: 'Mongolian Tugrik', code: 'MNT', symbol: '₮' },
  { name: 'Myanmar Kyat', code: 'MMK', symbol: 'K' },
  { name: 'Nepalese Rupee', code: 'NPR', symbol: '₨' },
  { name: 'Netherlands Antillean Guilder', code: 'ANG', symbol: 'ƒ' },
  { name: 'New Zealand Dollar', code: 'NZD', symbol: '$' },
  { name: 'Nicaraguan Córdoba', code: 'NIO', symbol: 'C$' },
  { name: 'North Korean Won', code: 'KPW', symbol: '₩' },
  { name: 'Norwegian Krone', code: 'NOK', symbol: 'kr' },
  { name: 'Omani Rial', code: 'OMR', symbol: '﷼' },
  { name: 'Pakistani Rupee', code: 'PKR', symbol: '₨' },
  { name: 'Panamanian Balboa', code: 'PAB', symbol: 'B/.' },
  { name: 'Papua New Guinean Kina', code: 'PGK', symbol: 'K' },
  { name: 'Paraguayan Guarani', code: 'PYG', symbol: '₲' },
  { name: 'Peruvian Sol', code: 'PEN', symbol: 'S/.' },
  { name: 'Philippine Peso', code: 'PHP', symbol: '₱' },
  { name: 'Polish Zloty', code: 'PLN', symbol: 'zł' },
  { name: 'Qatari Rial', code: 'QAR', symbol: '﷼' },
  { name: 'Romanian Leu', code: 'RON', symbol: 'lei' },
  { name: 'Samoan Tala', code: 'WST', symbol: 'T' },
  { name: 'Saudi Riyal', code: 'SAR', symbol: '﷼' },
  { name: 'Serbian Dinar', code: 'RSD', symbol: 'дин.' },
  { name: 'Singapore Dollar', code: 'SGD', symbol: '$' },
  { name: 'Solomon Islands Dollar', code: 'SBD', symbol: '$' },
  { name: 'South Korean Won', code: 'KRW', symbol: '₩' },
  { name: 'Sri Lankan Rupee', code: 'LKR', symbol: '₨' },
  { name: 'Surinamese Dollar', code: 'SRD', symbol: '$' },
  { name: 'Swedish Krona', code: 'SEK', symbol: 'kr' },
  { name: 'Syrian Pound', code: 'SYP', symbol: '£' },
  { name: 'New Taiwan Dollar', code: 'TWD', symbol: 'NT$' },
  { name: 'Tajikistani Somoni', code: 'TJS', symbol: 'ЅМ' },
  { name: 'Thai Baht', code: 'THB', symbol: '฿' },
  { name: 'Tongan Paʻanga', code: 'TOP', symbol: 'T$' },
  { name: 'Trinidad and Tobago Dollar', code: 'TTD', symbol: 'TT$' },
  { name: 'Turkish Lira', code: 'TRY', symbol: '₺' },
  { name: 'Turkmenistani Manat', code: 'TMT', symbol: 'm' },
  { name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴' },
  { name: 'United Arab Emirates Dirham', code: 'AED', symbol: 'د.إ' },
  { name: 'Uruguayan Peso', code: 'UYU', symbol: '$U' },
  { name: 'Uzbekistan Som', code: 'UZS', symbol: 'сўм' },
  { name: 'Vanuatu Vatu', code: 'VUV', symbol: 'VT' },
  { name: 'Venezuelan Bolívar', code: 'VES', symbol: 'Bs.' },
  { name: 'Vietnamese Dong', code: 'VND', symbol: '₫' },
  { name: 'Yemeni Rial', code: 'YER', symbol: '﷼' },
];
